/**
 * lich-am/js/licham-data.js — Nội dung chữ cho module Lịch Âm.
 *
 * Phân vai rõ: js/amlich.js cho SỐ (ngày nào, can chi gì, tiết khí bắt đầu lúc nào),
 * file này cho CHỮ (tiết khí ấy nghĩa là gì, lễ hôm đó là lễ gì).
 * scripts/build-licham-pages.mjs nạp bằng new Function(src + '; return LICHAM_DATA;').
 *
 * Lưu ý về tiết khí: hệ 24 tiết khí hình thành ở lưu vực Hoàng Hà nên mô tả khí hậu
 * bám sát miền Bắc Việt Nam nhất; miền Nam gần như chỉ có hai mùa mưa/khô nên phần
 * "khí hậu" mang tính tham chiếu. Đã ghi chú điều này trong nội dung thay vì lờ đi.
 *
 * Thứ tự TIET_KHI PHẢI khớp index của AmLich.TIET_KHI (0 = Xuân Phân, +15° mỗi mục).
 *
 * Globals: LICHAM_DATA
 */
const LICHAM_DATA = {
  TIET_KHI: [
    {
      i: 0, ten: 'Xuân Phân', slug: 'xuan-phan', kinhDo: 0, mua: 'Xuân',
      han: 'giữa mùa xuân, ngày và đêm dài bằng nhau',
      tomTat: 'Ngày dài bằng đêm, chính giữa mùa xuân.',
      khiHau: 'Mặt trời chiếu thẳng xích đạo nên ngày và đêm dài gần bằng nhau trên khắp cả nước. Miền Bắc lúc này ẩm nhất năm — nồm ẩm, tường và sàn nhà "đổ mồ hôi", quần áo phơi mãi không khô. Miền Nam bắt đầu những cơn mưa chuyển mùa đầu tiên sau mấy tháng khô hạn.',
      nongVu: 'Lúa chiêm xuân ở đồng bằng Bắc Bộ đang đẻ nhánh rộ, cần giữ nước nông và bón thúc đúng lúc. Đây cũng là thời điểm trồng rau màu vụ xuân, chăm cây ăn quả sau khi đậu trái.',
      sucKhoe: 'Độ ẩm cao là môi trường lý tưởng cho nấm mốc và vi khuẩn — dễ phát sinh bệnh hô hấp, dị ứng, viêm da. Nên hút ẩm, giữ nhà thông thoáng, hạn chế đồ ăn lạnh và nhiều dầu mỡ.',
      phongTuc: 'Tiết Xuân Phân xưa gắn với lễ tế mặt trời và các hội làng mùa xuân. Người Việt vẫn giữ nếp đi lễ chùa cầu an trong khoảng tháng Hai âm lịch, khi hội hè còn kéo dài sau Tết.',
    },
    {
      i: 1, ten: 'Thanh Minh', slug: 'thanh-minh', kinhDo: 15, mua: 'Xuân',
      han: 'trời trong, khí sáng',
      tomTat: 'Tiết tảo mộ — trời quang đãng, con cháu về sửa sang phần mộ tổ tiên.',
      khiHau: 'Trời hửng nắng, không khí trong trẻo hơn hẳn những ngày nồm trước đó. Nhiệt độ miền Bắc lên dần, mưa phùn thưa đi. Đây là quãng dễ chịu nhất của mùa xuân.',
      nongVu: 'Lúa chiêm xuân bước vào giai đoạn làm đòng — cần theo dõi sâu bệnh, nhất là đạo ôn và rầy. Vườn cây ăn quả cần tỉa cành, bón nuôi trái non.',
      sucKhoe: 'Thời tiết dễ chịu nhưng chênh lệch nhiệt độ ngày đêm còn lớn, dễ cảm lạnh khi đi tảo mộ sáng sớm. Người có bệnh xương khớp nên giữ ấm khớp gối khi ra đồng, ra nghĩa trang.',
      phongTuc: 'Tết Thanh Minh là dịp tảo mộ lớn nhất trong năm của người Việt: con cháu về quét dọn, đắp lại mộ phần, thắp hương mời tổ tiên. "Thanh minh trong tiết tháng ba / Lễ là tảo mộ, hội là đạp thanh" — câu Kiều mô tả đúng nếp này.',
    },
    {
      i: 2, ten: 'Cốc Vũ', slug: 'coc-vu', kinhDo: 30, mua: 'Xuân',
      han: 'mưa rào cho ngũ cốc',
      tomTat: 'Mưa xuống đều, hạt giống được nuôi — tiết cuối cùng của mùa xuân.',
      khiHau: 'Mưa rào bắt đầu nhiều hơn, lượng mưa tăng rõ so với đầu xuân. Miền Bắc ấm dần, thỉnh thoảng có dông đầu mùa. Miền Nam bước vào mùa mưa.',
      nongVu: 'Đúng như tên gọi, đây là tiết mưa nuôi ngũ cốc. Lúa làm đòng cần đủ nước; nông dân tranh thủ mưa để gieo trồng cây màu và chuẩn bị đất cho vụ hè thu.',
      sucKhoe: 'Ẩm và ấm khiến vi khuẩn sinh sôi nhanh, thức ăn dễ ôi thiu. Chú ý an toàn thực phẩm, uống đủ nước, phòng các bệnh tiêu hóa.',
      phongTuc: 'Cốc Vũ ít lễ riêng nhưng là mốc nông lịch quan trọng: hết Cốc Vũ là hết xuân, các việc gieo trồng vụ xuân phải xong xuôi.',
    },
    {
      i: 3, ten: 'Lập Hạ', slug: 'lap-ha', kinhDo: 45, mua: 'Hạ',
      han: 'bắt đầu mùa hạ',
      tomTat: 'Mở đầu mùa hạ — nắng bắt đầu gay gắt.',
      khiHau: 'Nhiệt độ tăng nhanh, miền Bắc xuất hiện những đợt nắng nóng đầu tiên, có thể kèm gió Lào ở Bắc Trung Bộ. Ngày dài rõ rệt hơn đêm.',
      nongVu: 'Thu hoạch lúa chiêm xuân ở nhiều nơi, đồng thời làm đất chuẩn bị vụ hè thu. Cây ăn quả vào giai đoạn nuôi trái, cần tưới đủ.',
      sucKhoe: 'Cơ thể chưa kịp thích nghi với nắng nóng nên dễ mệt, mất nước, say nắng. Nên uống nước rải đều trong ngày, tránh ra đường giờ nắng đỉnh, ăn nhiều rau quả mát.',
      phongTuc: 'Lập Hạ là mốc chuyển mùa; dân gian có tục ăn chè, ăn quả đầu mùa để "giải nhiệt", và bắt đầu chú ý phòng dịch bệnh mùa nóng.',
    },
    {
      i: 4, ten: 'Tiểu Mãn', slug: 'tieu-man', kinhDo: 60, mua: 'Hạ',
      han: 'hạt bắt đầu chắc, chưa đầy',
      tomTat: 'Hạt lúa bắt đầu mẩy nhưng chưa chín — mưa nhiều dần.',
      khiHau: 'Mưa tăng lên, độ ẩm cao, oi bức. Miền Bắc và miền Trung có thể có dông mạnh kèm lốc, mưa đá.',
      nongVu: 'Lúa hè thu ở phía Nam vào giai đoạn quan trọng. Ở phía Bắc, hạt lúa muộn bắt đầu chắc dần. Cần đề phòng ngập úng cục bộ sau dông.',
      sucKhoe: 'Nóng ẩm khiến mồ hôi khó bay hơi, dễ rôm sảy, nấm da, kiệt sức vì nóng. Mặc đồ thoáng, tắm rửa sạch, bổ sung điện giải khi lao động ngoài trời.',
      phongTuc: 'Không có lễ lớn; đây là tiết nông dân bận rộn nhất giữa hai vụ, dân gian coi trọng việc "trông trời trông đất trông mây" để né dông.',
    },
    {
      i: 5, ten: 'Mang Chủng', slug: 'mang-chung', kinhDo: 75, mua: 'Hạ',
      han: 'lúa trổ râu, mùa gieo cấy gấp',
      tomTat: 'Mùa gặt và gieo dồn dập — bận nhất của nhà nông.',
      khiHau: 'Nắng nóng đỉnh điểm xen mưa rào. Miền Bắc oi ả, miền Nam mưa đều.',
      nongVu: 'Tên tiết nói lên tất cả: vừa gặt lúa chín vừa phải gieo cấy vụ sau cho kịp thời vụ. Chậm một tuần có thể mất cả vụ, nên dân gian gọi là "tháng chạy đồng".',
      sucKhoe: 'Lao động cường độ cao dưới nắng dễ gây say nắng, chuột rút, tụt huyết áp. Nên làm sớm hoặc chiều muộn, nghỉ giữa buổi, uống nước có muối loãng.',
      phongTuc: 'Ở Việt Nam, tiết này thường trùng quãng Tết Đoan Ngọ (mùng 5 tháng Năm âm lịch) — tục "giết sâu bọ", ăn rượu nếp và trái cây chua từ sáng sớm.',
    },
    {
      i: 6, ten: 'Hạ Chí', slug: 'ha-chi', kinhDo: 90, mua: 'Hạ',
      han: 'cực điểm của mùa hạ',
      tomTat: 'Ngày dài nhất năm — mặt trời lên cao nhất ở Bắc bán cầu.',
      khiHau: 'Mặt trời chiếu thẳng chí tuyến Bắc, ngày dài nhất và đêm ngắn nhất trong năm. Nắng gắt, nền nhiệt cao, nhưng chưa phải lúc nóng nhất — nóng đỉnh sẽ đến sau vài tuần khi mặt đất tích đủ nhiệt.',
      nongVu: 'Chăm sóc lúa hè thu, tưới tiêu là việc chính. Cây trồng cần che chắn, giữ ẩm gốc.',
      sucKhoe: 'Đây là quãng dễ mất ngủ vì đêm ngắn và nóng. Y học cổ truyền coi Hạ Chí là lúc dương khí cực thịnh, khuyên ngủ trưa ngắn, ăn thanh đạm, tránh giận dữ.',
      phongTuc: 'Người xưa tế đất vào Hạ Chí (đối lại với tế trời vào Đông Chí). Dân gian Việt ít giữ lễ này nhưng vẫn coi Hạ Chí là mốc "sang nửa năm".',
    },
    {
      i: 7, ten: 'Tiểu Thử', slug: 'tieu-thu', kinhDo: 105, mua: 'Hạ',
      han: 'nắng nóng vừa',
      tomTat: 'Bắt đầu chuỗi ngày nóng nhất năm.',
      khiHau: 'Nóng rõ rệt, miền Bắc bước vào cao điểm nắng nóng kèm ẩm. Mùa mưa bão bắt đầu manh nha ở Biển Đông.',
      nongVu: 'Chăm bón lúa hè thu, phòng sâu bệnh phát triển mạnh trong điều kiện nóng ẩm. Chuẩn bị phương án tiêu úng khi mưa bão.',
      sucKhoe: 'Dễ mất nước và rối loạn điện giải. Người già và trẻ nhỏ cần đặc biệt chú ý; không tắm ngay khi vừa đi nắng về, không để quạt/điều hòa thốc thẳng vào người khi đang ra mồ hôi.',
      phongTuc: 'Dân gian bắt đầu chú ý xem thời tiết để dự đoán mùa bão: "Tiểu Thử mà mưa, mùa sau đỡ hạn".',
    },
    {
      i: 8, ten: 'Đại Thử', slug: 'dai-thu', kinhDo: 120, mua: 'Hạ',
      han: 'nắng nóng gay gắt nhất',
      tomTat: 'Nóng đỉnh điểm của cả năm.',
      khiHau: 'Thường là quãng nóng nhất năm ở miền Bắc, nhiệt độ có thể vượt 38-40°C. Mưa dông chiều tối nhiều, độ ẩm cao khiến cảm giác oi bức tăng thêm.',
      nongVu: 'Giữ nước cho ruộng, chống hạn cục bộ, đồng thời sẵn sàng tiêu úng khi có bão. Vật nuôi cần chuồng trại thoáng, đủ nước.',
      sucKhoe: 'Nguy cơ say nắng, sốc nhiệt cao nhất trong năm. Hạn chế ra ngoài từ 11h đến 15h; bù nước liên tục; cẩn thận khi vào ra phòng lạnh đột ngột.',
      phongTuc: 'Y học cổ truyền có tục "đông bệnh hạ trị" — chữa bệnh mùa đông vào ngày nóng nhất, như cứu ngải, dán cao huyệt vào tam phục.',
    },
    {
      i: 9, ten: 'Lập Thu', slug: 'lap-thu', kinhDo: 135, mua: 'Thu',
      han: 'bắt đầu mùa thu',
      tomTat: 'Mở đầu mùa thu — nhưng nắng nóng chưa dứt ngay.',
      khiHau: 'Về lịch pháp là sang thu, nhưng thực tế miền Bắc vẫn còn "nắng thu oi" kéo dài vài tuần. Đêm bắt đầu dịu hơn. Đây cũng là cao điểm mùa bão ở Biển Đông.',
      nongVu: 'Thu hoạch lúa hè thu ở phía Nam, chăm lúa mùa ở phía Bắc. Gia cố bờ vùng, khơi thông mương máng phòng bão lụt.',
      sucKhoe: 'Chuyển mùa khiến cơ thể dễ hụt hơi, khô họng. Y học cổ truyền nói thu táo hại phế — nên ăn đồ nhuận phổi như lê, mật ong, củ sen.',
      phongTuc: 'Tiết này thường gần Rằm tháng Bảy — lễ Vu Lan báo hiếu và cúng cô hồn, một trong hai rằm lớn nhất năm của người Việt.',
    },
    {
      i: 10, ten: 'Xử Thử', slug: 'xu-thu', kinhDo: 150, mua: 'Thu',
      han: 'chấm dứt nắng nóng',
      tomTat: 'Cái nóng rút lui, trời bắt đầu mát về đêm.',
      khiHau: 'Nắng nóng giảm hẳn, sáng sớm và đêm se mát. Miền Bắc dễ chịu dần; miền Trung vào cao điểm mưa bão.',
      nongVu: 'Chăm sóc lúa mùa giai đoạn đẻ nhánh, làm cỏ, bón thúc. Đề phòng bão gây đổ ngã.',
      sucKhoe: 'Chênh lệch nhiệt độ ngày đêm lớn dần — dễ cảm, viêm họng. Nên đắp chăn mỏng khi ngủ, không để quạt thổi suốt đêm.',
      phongTuc: 'Nông lịch coi Xử Thử là mốc "hết nóng"; nhiều nơi bắt đầu chuẩn bị cho các lễ hội mùa thu.',
    },
    {
      i: 11, ten: 'Bạch Lộ', slug: 'bach-lo', kinhDo: 165, mua: 'Thu',
      han: 'sương trắng đọng',
      tomTat: 'Sương trắng bắt đầu đọng trên lá lúc sớm mai.',
      khiHau: 'Đêm lạnh đủ để hơi nước ngưng thành sương. Trời hanh, nắng vàng, độ ẩm giảm — quãng đẹp nhất của mùa thu miền Bắc.',
      nongVu: 'Lúa mùa làm đòng, cần đủ nước và phòng sâu cuốn lá. Trồng rau vụ đông sớm.',
      sucKhoe: 'Không khí hanh khô gây khô da, khô mũi họng. Uống đủ nước, dưỡng ẩm da, buổi sáng ra đường nên khoác thêm áo mỏng.',
      phongTuc: 'Tiết này hay trùng Tết Trung Thu (Rằm tháng Tám) — trăng sáng nhất năm, phá cỗ, rước đèn, ngắm trăng.',
    },
    {
      i: 12, ten: 'Thu Phân', slug: 'thu-phan', kinhDo: 180, mua: 'Thu',
      han: 'giữa mùa thu, ngày đêm bằng nhau',
      tomTat: 'Ngày dài bằng đêm lần thứ hai trong năm, chính giữa mùa thu.',
      khiHau: 'Mặt trời lại chiếu thẳng xích đạo. Từ đây đêm sẽ dài hơn ngày cho tới Xuân Phân năm sau. Miền Bắc mát mẻ, khô ráo; miền Trung mưa lũ nhiều nhất.',
      nongVu: 'Lúa mùa trổ bông. Chuẩn bị đất và giống cho vụ đông. Vùng thấp cần theo dõi lũ.',
      sucKhoe: 'Âm dương cân bằng, y học cổ truyền khuyên ăn uống điều độ, ngủ sớm dậy sớm, dưỡng phế và tránh ưu tư quá độ.',
      phongTuc: 'Người xưa tế trăng vào Thu Phân. Ở Việt Nam, không khí Trung Thu thường còn kéo dài quanh tiết này.',
    },
    {
      i: 13, ten: 'Hàn Lộ', slug: 'han-lo', kinhDo: 195, mua: 'Thu',
      han: 'sương lạnh',
      tomTat: 'Sương đã lạnh, hơi thu rõ rệt.',
      khiHau: 'Không khí lạnh đầu mùa bắt đầu tràn về miền Bắc từng đợt. Trời hanh khô, nắng nhạt, sáng sớm lạnh tay.',
      nongVu: 'Thu hoạch lúa mùa sớm, gieo trồng rau màu vụ đông như ngô, khoai, su hào, bắp cải.',
      sucKhoe: 'Đợt lạnh đầu mùa dễ khiến người có bệnh tim mạch, huyết áp trở nặng. Giữ ấm chân và cổ, tăng vận động nhẹ buổi sáng nhưng tránh ra ngoài quá sớm khi trời còn rét.',
      phongTuc: 'Tiết này gắn với thói quen "trở chăn đệm", cất đồ mùa hè, sửa soạn áo ấm cho mùa lạnh.',
    },
    {
      i: 14, ten: 'Sương Giáng', slug: 'suong-giang', kinhDo: 210, mua: 'Thu',
      han: 'sương muối xuống',
      tomTat: 'Tiết cuối mùa thu — sương muối có thể xuất hiện ở vùng cao.',
      khiHau: 'Rét đậm đầu tiên có thể xuất hiện ở vùng núi phía Bắc, kèm sương muối gây hại cây trồng. Đồng bằng se lạnh, hanh khô.',
      nongVu: 'Thu hoạch nốt lúa mùa, chăm rau vụ đông. Vùng cao cần che chắn mạ và gia súc chống sương muối, rét hại.',
      sucKhoe: 'Khô hanh cộng lạnh dễ gây nứt nẻ da, chảy máu cam, viêm phế quản. Giữ ẩm không khí trong nhà, ăn thức ăn ấm.',
      phongTuc: 'Hết Sương Giáng là hết thu. Dân gian bắt đầu tính chuyện chuẩn bị lương thực và củi lửa cho mùa đông.',
    },
    {
      i: 15, ten: 'Lập Đông', slug: 'lap-dong', kinhDo: 225, mua: 'Đông',
      han: 'bắt đầu mùa đông',
      tomTat: 'Mở đầu mùa đông — vạn vật thu mình tích trữ.',
      khiHau: 'Gió mùa đông bắc về đều đặn hơn, miền Bắc lạnh dần. Miền Nam bước vào mùa khô, trời mát và ít mưa.',
      nongVu: 'Chăm sóc cây vụ đông, chống rét cho mạ và gia súc. Nhiều nơi bắt đầu làm đất cho vụ chiêm xuân.',
      sucKhoe: 'Y học cổ truyền coi mùa đông là mùa "tàng" — nên ngủ sớm dậy muộn hơn, ăn ấm và bổ, giữ ấm vùng lưng và bàn chân.',
      phongTuc: 'Lập Đông là mốc để "bồi bổ mùa đông"; nhiều gia đình bắt đầu nấu các món hầm, cháo bổ để giữ sức qua rét.',
    },
    {
      i: 16, ten: 'Tiểu Tuyết', slug: 'tieu-tuyet', kinhDo: 240, mua: 'Đông',
      han: 'tuyết nhẹ',
      tomTat: 'Rét tăng — tên tiết nói về tuyết ở phương Bắc, Việt Nam là rét khô.',
      khiHau: 'Tên gọi bắt nguồn từ khí hậu Trung Hoa; ở Việt Nam gần như không có tuyết trừ vài đỉnh núi cao như Fansipan, Mẫu Sơn trong đợt rét kỷ lục. Thực tế miền Bắc là rét khô kèm hanh.',
      nongVu: 'Chống rét cho mạ xuân và gia súc là việc quan trọng nhất. Thu hoạch rau vụ đông.',
      sucKhoe: 'Rét khô làm da nứt nẻ, môi khô. Người cao tuổi cần tránh ra ngoài sáng sớm — thời điểm huyết áp dễ tăng vọt.',
      phongTuc: 'Dân gian bắt đầu tính lịch tất niên, chuẩn bị các việc cuối năm âm lịch.',
    },
    {
      i: 17, ten: 'Đại Tuyết', slug: 'dai-tuyet', kinhDo: 255, mua: 'Đông',
      han: 'tuyết dày',
      tomTat: 'Cao điểm rét của tiết đông — trước Đông Chí.',
      khiHau: 'Các đợt không khí lạnh mạnh liên tiếp tràn xuống. Vùng núi cao Bắc Bộ có thể xuống dưới 0°C, xuất hiện băng giá.',
      nongVu: 'Bảo vệ mạ, che phủ nilon, giữ nước ấm cho ruộng mạ. Gia súc cần chuồng kín gió và thức ăn dự trữ.',
      sucKhoe: 'Nguy cơ đột quỵ và các biến cố tim mạch tăng rõ trong đợt rét sâu. Không tắm khuya, giữ ấm khi ngủ, khởi động kỹ trước khi ra ngoài trời lạnh.',
      phongTuc: 'Đây là quãng người xưa "cất mình" nghỉ ngơi, tổng kết một năm lao động.',
    },
    {
      i: 18, ten: 'Đông Chí', slug: 'dong-chi', kinhDo: 270, mua: 'Đông',
      han: 'cực điểm của mùa đông',
      tomTat: 'Đêm dài nhất năm — và cũng là mốc dương khí bắt đầu sinh trở lại.',
      khiHau: 'Mặt trời xuống thấp nhất, ngày ngắn nhất và đêm dài nhất trong năm. Rét đậm, nhưng như Hạ Chí, cái rét sâu nhất sẽ đến sau đó vài tuần.',
      nongVu: 'Tiếp tục chống rét, chuẩn bị giống và đất cho vụ chiêm xuân.',
      sucKhoe: 'Y học cổ truyền coi Đông Chí là thời điểm "nhất dương sinh" — âm cực thịnh, dương bắt đầu nhen. Đây là lúc bồi bổ hiệu quả nhất trong năm, nên ngủ đủ, ăn ấm, tránh hao tổn sức.',
      phongTuc: 'Đông Chí là tiết khí quan trọng bậc nhất trong lịch pháp — mốc để xác định tháng Mười Một âm lịch, từ đó suy ra toàn bộ tháng nhuận của năm. Người xưa tế trời vào ngày này.',
    },
    {
      i: 19, ten: 'Tiểu Hàn', slug: 'tieu-han', kinhDo: 285, mua: 'Đông',
      han: 'rét nhẹ',
      tomTat: 'Rét bắt đầu vào giai đoạn khắc nghiệt nhất.',
      khiHau: 'Dù tên là "rét nhẹ", đây thường đã là một trong những quãng lạnh nhất năm ở miền Bắc, với rét đậm rét hại kéo dài.',
      nongVu: 'Chống rét cho mạ và gia súc vẫn là việc chính. Chuẩn bị gieo cấy vụ chiêm xuân khi trời ấm lên.',
      sucKhoe: 'Giữ ấm tuyệt đối cho người già và trẻ nhỏ. Cẩn thận với than sưởi trong phòng kín — ngộ độc khí CO là tai nạn xảy ra hằng năm ở nông thôn miền Bắc.',
      phongTuc: 'Quãng này thường trùng tháng Chạp — không khí sắm Tết bắt đầu rộn ràng.',
    },
    {
      i: 20, ten: 'Đại Hàn', slug: 'dai-han', kinhDo: 300, mua: 'Đông',
      han: 'rét đậm nhất',
      tomTat: 'Tiết cuối cùng của năm tiết khí — rét sâu nhất rồi ấm dần.',
      khiHau: 'Thường là quãng rét nhất, nhưng cũng là lúc rét bắt đầu suy. Cuối Đại Hàn trời hửng dần, báo hiệu xuân sang.',
      nongVu: 'Làm đất, ngâm ủ giống, chờ ấm để cấy vụ chiêm xuân. Tiếp tục che chắn chống rét.',
      sucKhoe: 'Vẫn là cao điểm bệnh hô hấp và tim mạch. Ăn đủ chất, vận động vừa phải trong nhà, tránh thay đổi nhiệt độ đột ngột.',
      phongTuc: 'Đại Hàn rơi vào cận Tết — dọn dẹp nhà cửa, cúng ông Công ông Táo (23 tháng Chạp), tất niên. Hết Đại Hàn là tới Lập Xuân, khép trọn một vòng 24 tiết.',
    },
    {
      i: 21, ten: 'Lập Xuân', slug: 'lap-xuan', kinhDo: 315, mua: 'Xuân',
      han: 'bắt đầu mùa xuân',
      tomTat: 'Khởi đầu một vòng tiết khí mới — mốc sang năm can chi.',
      khiHau: 'Trời ấm dần, mưa phùn xuất hiện. Rét vẫn còn nhưng đã có nắng xuân xen kẽ. Cây cối bắt đầu nảy lộc.',
      nongVu: 'Vào vụ cấy chiêm xuân — vụ lúa lớn nhất năm ở miền Bắc. Trồng cây đầu xuân, chăm vườn sau Tết.',
      sucKhoe: 'Thời tiết thất thường, nóng lạnh đan xen, dễ cảm cúm. Mặc nhiều lớp để dễ điều chỉnh; y học cổ truyền khuyên "xuân tiệm giảm y" — cởi bớt áo từ từ, đừng vội.',
      phongTuc: 'Lập Xuân là mốc đổi năm can chi trong tử vi và trạch nhật: người sinh trước Lập Xuân vẫn tính con giáp năm cũ, dù đã qua Tết Nguyên Đán. Đây là điểm rất hay bị nhầm khi xem tuổi.',
    },
    {
      i: 22, ten: 'Vũ Thủy', slug: 'vu-thuy', kinhDo: 330, mua: 'Xuân',
      han: 'mưa ẩm',
      tomTat: 'Mưa xuân lất phất, độ ẩm lên cao.',
      khiHau: 'Mưa phùn dày hơn, nồm ẩm bắt đầu. Nhiệt độ nhích lên, sương mù nhiều vào sáng sớm.',
      nongVu: 'Cấy chiêm xuân rộ, tận dụng mưa ẩm để bén rễ. Chăm sóc cây trồng vừa xuống giống.',
      sucKhoe: 'Nồm ẩm khiến nấm mốc phát triển — người bị hen suyễn, viêm mũi dị ứng dễ tái phát. Nên lau khô sàn, dùng máy hút ẩm, phơi chăn màn khi có nắng.',
      phongTuc: 'Quãng này còn trong mùa lễ hội đầu năm: hội chùa, hội làng kéo dài suốt tháng Giêng, tháng Hai âm lịch.',
    },
    {
      i: 23, ten: 'Kinh Trập', slug: 'kinh-trap', kinhDo: 345, mua: 'Xuân',
      han: 'sâu bọ thức giấc sau tiếng sấm',
      tomTat: 'Sấm xuân đầu tiên đánh thức côn trùng ngủ đông.',
      khiHau: 'Sấm xuân bắt đầu xuất hiện, trời ấm lên rõ. Mưa phùn xen dông nhẹ. Đây là tiết cuối trước Xuân Phân.',
      nongVu: 'Chăm lúa mới cấy, làm cỏ, bón thúc lần đầu. Đặc biệt phải phòng sâu bệnh vì côn trùng bắt đầu hoạt động mạnh trở lại.',
      sucKhoe: 'Thời tiết ấm ẩm là điều kiện cho vi khuẩn, virus phát triển — mùa cúm và bệnh truyền nhiễm. Giữ vệ sinh, tiêm phòng, ăn chín uống sôi.',
      phongTuc: 'Tên tiết gắn với hình ảnh tiếng sấm đầu mùa. Nông dân xưa lấy Kinh Trập làm mốc để bắt đầu diệt trừ sâu bọ cho đồng ruộng.',
    },
  ],

  // Lễ tết đánh dấu trên lịch. lich: 'am' = ngày âm, 'duong' = ngày dương.
  LE_TET: [
    { lich: 'am', d: 1,  m: 1,  ten: 'Tết Nguyên Đán', mo: 'Ngày đầu năm âm lịch, lễ lớn nhất trong năm của người Việt: sum họp gia đình, cúng gia tiên, chúc Tết và mừng tuổi.' },
    { lich: 'am', d: 15, m: 1,  ten: 'Tết Nguyên Tiêu', mo: 'Rằm tháng Giêng, "lễ Phật quanh năm không bằng Rằm tháng Giêng" — ngày đi lễ chùa cầu an đông nhất đầu năm.' },
    { lich: 'am', d: 3,  m: 3,  ten: 'Tết Hàn Thực', mo: 'Ngày làm bánh trôi bánh chay dâng cúng tổ tiên.' },
    { lich: 'am', d: 10, m: 3,  ten: 'Giỗ Tổ Hùng Vương', mo: 'Quốc lễ tưởng nhớ các Vua Hùng, cũng là ngày nghỉ lễ theo lịch dương tương ứng.' },
    { lich: 'am', d: 15, m: 4,  ten: 'Lễ Phật Đản', mo: 'Kỷ niệm ngày Đức Phật đản sinh, các chùa tổ chức lễ tắm Phật và rước xe hoa.' },
    { lich: 'am', d: 5,  m: 5,  ten: 'Tết Đoan Ngọ', mo: 'Tết "giết sâu bọ" — ăn rượu nếp, trái cây chua vào sáng sớm để trừ bệnh tật.' },
    { lich: 'am', d: 15, m: 7,  ten: 'Rằm tháng Bảy — Vu Lan', mo: 'Lễ Vu Lan báo hiếu cha mẹ, đồng thời là ngày xá tội vong nhân, cúng cô hồn.' },
    { lich: 'am', d: 15, m: 8,  ten: 'Tết Trung Thu', mo: 'Tết trông trăng của trẻ em: rước đèn, phá cỗ, múa lân, ngắm trăng tròn nhất năm.' },
    { lich: 'am', d: 9,  m: 9,  ten: 'Tết Trùng Cửu', mo: 'Ngày lên cao ngắm cảnh, uống rượu hoa cúc theo tục xưa.' },
    { lich: 'am', d: 10, m: 10, ten: 'Tết Thường Tân', mo: 'Tết cơm mới, tạ ơn trời đất sau vụ gặt.' },
    { lich: 'am', d: 23, m: 12, ten: 'Ông Công Ông Táo', mo: 'Tiễn Táo quân về trời bằng cá chép, mở đầu chuỗi việc chuẩn bị Tết.' },
    { lich: 'am', d: 30, m: 12, ten: 'Giao thừa (Tất niên)', mo: 'Đêm cuối năm âm lịch, cúng tất niên và đón giao thừa. Năm tháng Chạp thiếu thì rơi vào ngày 29.' },
    { lich: 'duong', d: 1,  m: 1,  ten: 'Tết Dương Lịch', mo: 'Ngày đầu năm dương lịch, nghỉ lễ theo quy định.' },
    { lich: 'duong', d: 14, m: 2,  ten: 'Lễ Tình Nhân', mo: 'Valentine — ngày của các cặp đôi.' },
    { lich: 'duong', d: 8,  m: 3,  ten: 'Quốc tế Phụ nữ', mo: 'Ngày tôn vinh phụ nữ.' },
    { lich: 'duong', d: 30, m: 4,  ten: 'Ngày Giải phóng miền Nam', mo: 'Kỷ niệm ngày thống nhất đất nước, nghỉ lễ.' },
    { lich: 'duong', d: 1,  m: 5,  ten: 'Quốc tế Lao động', mo: 'Ngày nghỉ lễ của người lao động.' },
    { lich: 'duong', d: 1,  m: 6,  ten: 'Quốc tế Thiếu nhi', mo: 'Ngày dành cho trẻ em.' },
    { lich: 'duong', d: 2,  m: 9,  ten: 'Quốc khánh', mo: 'Kỷ niệm ngày Tuyên ngôn Độc lập 2/9/1945, nghỉ lễ.' },
    { lich: 'duong', d: 20, m: 10, ten: 'Ngày Phụ nữ Việt Nam', mo: 'Ngày tôn vinh phụ nữ Việt Nam.' },
    { lich: 'duong', d: 20, m: 11, ten: 'Ngày Nhà giáo Việt Nam', mo: 'Ngày tri ân thầy cô.' },
    { lich: 'duong', d: 24, m: 12, ten: 'Đêm Giáng Sinh', mo: 'Lễ Noel, đông vui ở các thành phố lớn và vùng có đông đồng bào Công giáo.' },
  ],
};

if (typeof window !== 'undefined') window.LICHAM_DATA = LICHAM_DATA;
