/**
 * scripts/build-icons.mjs — regenerate the self-hosted Tabler icon subset.
 *
 * Scans the codebase for every `ti ti-*` class actually used, downloads the
 * pinned Tabler webfont, subsets it down to just those glyphs, writes
 * fonts/tabler-icons-subset.woff2, and rewrites the icon rules in
 * css/common.css between the TABLER-ICONS:START / :END markers.
 *
 * Requires: Python with fonttools + brotli  (pip install fonttools brotli)
 * Run:      node scripts/build-icons.mjs
 */
import fs from 'fs';
import os from 'os';
import path from 'path';
import { execFileSync } from 'child_process';

const VERSION = '3.44.0';
const CSS_URL = `https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@${VERSION}/dist/tabler-icons.min.css`;
const WOFF_URL = `https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@${VERSION}/dist/fonts/tabler-icons.woff2`;
const OUT_WOFF = 'fonts/tabler-icons-subset.woff2';
const COMMON_CSS = 'css/common.css';
const START = '/* TABLER-ICONS:START';
const END = '/* TABLER-ICONS:END */';

// 1. Collect used icon names from HTML/JS
const SCAN_EXT = new Set(['.html', '.js']);
const SKIP_DIR = new Set(['node_modules', '.git', '.tmp-icons', 'fonts', 'scripts']);
function walk(dir, acc = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith('.') && e.name !== '.') continue;
    if (e.isDirectory()) { if (!SKIP_DIR.has(e.name)) walk(path.join(dir, e.name), acc); }
    else if (SCAN_EXT.has(path.extname(e.name))) acc.push(path.join(dir, e.name));
  }
  return acc;
}
const used = new Set();
for (const f of walk('.')) {
  const txt = fs.readFileSync(f, 'utf8');
  for (const m of txt.matchAll(/\bti ti-([a-z0-9-]+)/g)) used.add(m[1]);
}
const icons = [...used].sort();
console.log(`Found ${icons.length} distinct icons in use.`);

// 2. Download pinned Tabler CSS + woff2
async function dl(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`download failed ${r.status}: ${url}`);
  return Buffer.from(await r.arrayBuffer());
}
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'tbl-'));
const cssTxt = (await dl(CSS_URL)).toString('utf8');
const woffPath = path.join(tmp, 'full.woff2');
fs.writeFileSync(woffPath, await dl(WOFF_URL));

// 3. Map names -> codepoints; fail loudly on any missing (= broken icon in markup)
const map = {};
for (const m of cssTxt.matchAll(/\.ti-([a-z0-9-]+):before\{content:"\\([0-9a-fA-F]+)"\}/g)) map[m[1]] = m[2];
const missing = icons.filter((n) => !map[n]);
if (missing.length) throw new Error(`Icons not found in Tabler ${VERSION}: ${missing.join(', ')}`);
const codes = icons.map((n) => 'U+' + map[n].toUpperCase());
const rules = icons.map((n) => `.ti-${n}:before{content:"\\${map[n]}"}`).join('\n');

// 4. Subset the font
fs.mkdirSync('fonts', { recursive: true });
execFileSync('pyftsubset', [
  woffPath,
  `--unicodes=${codes.join(',')}`,
  '--flavor=woff2',
  `--output-file=${OUT_WOFF}`,
], { stdio: 'inherit' });
console.log(`Wrote ${OUT_WOFF} (${fs.statSync(OUT_WOFF).size} bytes)`);

// 5. Rewrite the icon block in common.css between the markers
const block =
`${START} — generated by \`node scripts/build-icons.mjs\`, do not edit by hand.
   Self-hosted subset (only the glyphs used sitewide) replacing the 457KB CDN webfont. */
@font-face {
  font-family: "tabler-icons";
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url("/fonts/tabler-icons-subset.woff2") format("woff2");
}
.ti {
  font-family: "tabler-icons" !important;
  font-style: normal; font-weight: normal; font-variant: normal; text-transform: none;
  speak: none; -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;
  line-height: 1; vertical-align: -0.125em; display: inline-block;
}
${rules}
${END}`;

let css = fs.readFileSync(COMMON_CSS, 'utf8');
const s = css.indexOf(START), e = css.indexOf(END);
if (s === -1 || e === -1) throw new Error('markers not found in common.css');
css = css.slice(0, s) + block + css.slice(e + END.length);
fs.writeFileSync(COMMON_CSS, css);
fs.rmSync(tmp, { recursive: true, force: true });
console.log('common.css icon block regenerated.');
