/**
 * tarot/js/cards-minor.js
 * 56 Minor Arcana — Vietnamese names, meanings, advice (Rider-Waite tradition).
 * img matches files in tarot/images/: w=Wands(Gậy), c=Cups(Cốc), s=Swords(Kiếm), p=Pentacles(Xu).
 * Rank 1=Át, 11=Tiểu Đồng (Page), 12=Hiệp Sĩ (Knight), 13=Hoàng Hậu (Queen), 14=Vua (King).
 */

const MINOR_ARCANA = [
  // ============ WANDS / GẬY — hành Lửa ============
  { img: 'w1',  name: 'Ace of Wands', vn: 'Át Gậy', suit: 'wands',
    keywords: ['Khởi đầu', 'Cảm hứng', 'Tiềm năng'],
    upright: 'Một tia lửa sáng tạo hoặc cơ hội mới vừa được thắp lên. Đây là tín hiệu xanh cho dự án, đam mê hay hành trình mới — năng lượng đang ở mức cao nhất.',
    reversed: 'Cảm hứng bị trì hoãn, dự án chậm khởi động hoặc bạn thiếu động lực. Ngọn lửa vẫn còn nhưng cần thời gian để bùng lên.',
    advice: 'Nắm lấy cơ hội ngay khi nó xuất hiện — đừng chờ điều kiện hoàn hảo.' },
  { img: 'w2',  name: 'Two of Wands', vn: '2 Gậy', suit: 'wands',
    keywords: ['Lập kế hoạch', 'Tầm nhìn', 'Quyết định'],
    upright: 'Bạn đang đứng trước bản đồ tương lai của chính mình, cân nhắc bước đi tiếp theo. Tầm nhìn xa và kế hoạch rõ ràng sẽ đưa bạn ra khỏi vùng an toàn.',
    reversed: 'Sợ thay đổi khiến bạn ở lại nơi quen thuộc dù lòng đã muốn đi. Kế hoạch thiếu thực tế hoặc bạn đang lưỡng lự quá lâu.',
    advice: 'Thế giới rộng hơn vùng an toàn của bạn — hãy lên kế hoạch và bước ra.' },
  { img: 'w3',  name: 'Three of Wands', vn: '3 Gậy', suit: 'wands',
    keywords: ['Mở rộng', 'Chờ kết quả', 'Tiến triển'],
    upright: 'Những nỗ lực ban đầu bắt đầu sinh trái — con thuyền bạn gửi đi đang quay về. Hãy tiếp tục mở rộng tầm nhìn, cơ hội từ xa đang đến.',
    reversed: 'Kế hoạch bị chậm trễ, kết quả chưa như kỳ vọng. Có thể bạn đã đánh giá thấp trở ngại hoặc tầm nhìn còn hạn hẹp.',
    advice: 'Kiên nhẫn — bạn đã gieo đúng, giờ là lúc chờ mùa gặt.' },
  { img: 'w4',  name: 'Four of Wands', vn: '4 Gậy', suit: 'wands',
    keywords: ['Ăn mừng', 'Ổn định', 'Sum họp'],
    upright: 'Thời khắc của lễ hội, đoàn tụ và những cột mốc đáng ăn mừng — đám cưới, tân gia, thành quả nhóm. Nền móng bạn xây đã vững.',
    reversed: 'Bất hòa trong gia đình hoặc cảm giác không thuộc về nơi mình đang sống. Niềm vui bị trì hoãn nhưng không mất đi.',
    advice: 'Dừng lại ăn mừng những gì đã đạt được trước khi đi tiếp.' },
  { img: 'w5',  name: 'Five of Wands', vn: '5 Gậy', suit: 'wands',
    keywords: ['Cạnh tranh', 'Xung đột', 'Thử thách'],
    upright: 'Va chạm, tranh đua và bất đồng quan điểm đang vây quanh bạn. Cuộc cạnh tranh này tuy mệt nhưng giúp bạn rèn bản lĩnh.',
    reversed: 'Xung đột đang lắng xuống hoặc bạn đang né tránh va chạm cần thiết. Đôi khi phải nói thẳng để giải tỏa.',
    advice: 'Cạnh tranh để tiến bộ, đừng cạnh tranh để hơn thua.' },
  { img: 'w6',  name: 'Six of Wands', vn: '6 Gậy', suit: 'wands',
    keywords: ['Chiến thắng', 'Công nhận', 'Tự hào'],
    upright: 'Chiến thắng công khai và sự công nhận từ người xung quanh đang đến. Bạn xứng đáng với vòng nguyệt quế này — hãy tự tin đón nhận.',
    reversed: 'Thành công bị trì hoãn hoặc nỗ lực không được ghi nhận. Đừng để cái tôi tổn thương làm bạn bỏ cuộc.',
    advice: 'Đón nhận lời khen nhưng đừng ngủ quên trên chiến thắng.' },
  { img: 'w7',  name: 'Seven of Wands', vn: '7 Gậy', suit: 'wands',
    keywords: ['Phòng thủ', 'Kiên định', 'Bảo vệ lập trường'],
    upright: 'Bạn đang ở thế phải bảo vệ vị trí, quan điểm hay thành quả trước nhiều áp lực. Lợi thế vẫn thuộc về bạn nếu giữ vững lập trường.',
    reversed: 'Bạn đang kiệt sức vì phải chống đỡ quá lâu, hoặc cảm thấy bị áp đảo. Cân nhắc trận nào đáng đánh, trận nào nên buông.',
    advice: 'Đứng vững — người ở trên đồi luôn có lợi thế.' },
  { img: 'w8',  name: 'Eight of Wands', vn: '8 Gậy', suit: 'wands',
    keywords: ['Tốc độ', 'Tin tức', 'Chuyển động nhanh'],
    upright: 'Mọi thứ đột ngột tăng tốc: tin tức, cơ hội, chuyến đi đến dồn dập. Hãy hành động nhanh và dứt khoát — vũ trụ đang mở đường.',
    reversed: 'Trì hoãn, lỡ nhịp hoặc vội vàng dẫn đến sai sót. Năng lượng phân tán khiến mọi việc rối loạn.',
    advice: 'Khi gió thuận, hãy giương buồm ngay lập tức.' },
  { img: 'w9',  name: 'Nine of Wands', vn: '9 Gậy', suit: 'wands',
    keywords: ['Bền bỉ', 'Cảnh giác', 'Chặng cuối'],
    upright: 'Bạn đã trầy trật qua nhiều trận chiến và đang ở rất gần đích. Mệt mỏi nhưng đừng buông — sức bền chính là vũ khí cuối cùng.',
    reversed: 'Kiệt quệ, hoài nghi và muốn bỏ cuộc ngay trước vạch đích. Hoặc bạn đang phòng thủ quá mức với cả người tốt.',
    advice: 'Còn một bước nữa thôi — gục ngã lúc này là uổng phí tất cả.' },
  { img: 'w10', name: 'Ten of Wands', vn: '10 Gậy', suit: 'wands',
    keywords: ['Gánh nặng', 'Trách nhiệm', 'Quá tải'],
    upright: 'Bạn đang ôm quá nhiều trách nhiệm một mình và gần đến giới hạn. Thành công đã có nhưng cái giá là sự quá tải.',
    reversed: 'Đã đến lúc buông bớt gánh nặng hoặc học cách giao việc. Giải phóng bản thân khỏi những trách nhiệm không phải của mình.',
    advice: 'Biết gánh là sức mạnh, biết buông là trí tuệ.' },
  { img: 'w11', name: 'Page of Wands', vn: 'Tiểu Đồng Gậy', suit: 'wands',
    keywords: ['Nhiệt huyết', 'Khám phá', 'Tin vui'],
    upright: 'Tinh thần phiêu lưu và tò mò đang dẫn lối — một tin vui hay ý tưởng mới đầy hứng khởi sắp đến. Hãy giữ tâm thế của người mới bắt đầu.',
    reversed: 'Nhiệt tình bốc đồng nhưng thiếu kiên trì, dễ bỏ dở giữa chừng. Tin tức chậm trễ hoặc gây thất vọng.',
    advice: 'Đam mê cần đi cùng cam kết mới thành sự nghiệp.' },
  { img: 'w12', name: 'Knight of Wands', vn: 'Hiệp Sĩ Gậy', suit: 'wands',
    keywords: ['Hành động', 'Đam mê', 'Bốc đồng'],
    upright: 'Năng lượng hành động mãnh liệt — lao về phía mục tiêu với tất cả đam mê. Phù hợp cho khởi sự táo bạo, chuyến đi xa, thay đổi lớn.',
    reversed: 'Hấp tấp, nóng nảy, hứa nhiều làm ít. Năng lượng mạnh nhưng thiếu định hướng dễ gây đổ vỡ.',
    advice: 'Cưỡi ngựa nhanh thì tới sớm, nhưng nhớ nhìn đường.' },
  { img: 'w13', name: 'Queen of Wands', vn: 'Hoàng Hậu Gậy', suit: 'wands',
    keywords: ['Tự tin', 'Cuốn hút', 'Độc lập'],
    upright: 'Hiện thân của sự tự tin rạng rỡ, ấm áp và truyền cảm hứng. Bạn (hoặc người này) làm chủ cuộc sống của mình và thắp lửa cho người khác.',
    reversed: 'Ghen tuông, đòi hỏi sự chú ý hoặc tự ti che giấu bằng vẻ ngoài mạnh mẽ. Ngọn lửa đang cháy ngược vào trong.',
    advice: 'Tỏa sáng theo cách của bạn — không cần ai cho phép.' },
  { img: 'w14', name: 'King of Wands', vn: 'Vua Gậy', suit: 'wands',
    keywords: ['Lãnh đạo', 'Tầm nhìn', 'Khởi nghiệp'],
    upright: 'Nhà lãnh đạo có tầm nhìn, dám nghĩ lớn và truyền lửa cho cả đội. Đây là lúc bước lên nắm quyền chủ động và dẫn dắt.',
    reversed: 'Độc đoán, nóng vội hoặc kỳ vọng quá cao vào người khác. Lãnh đạo bằng áp đặt sẽ mất người tài.',
    advice: 'Người lãnh đạo giỏi thắp lửa, không đốt cháy người khác.' },

  // ============ CUPS / CỐC — hành Nước ============
  { img: 'c1',  name: 'Ace of Cups', vn: 'Át Cốc', suit: 'cups',
    keywords: ['Tình cảm mới', 'Trực giác', 'Khởi đầu cảm xúc'],
    upright: 'Trái tim bạn đang mở ra đón nhận tình yêu, lòng trắc ẩn hoặc nguồn cảm hứng tinh thần mới. Một mối quan hệ hay giai đoạn cảm xúc đẹp đẽ bắt đầu.',
    reversed: 'Cảm xúc bị kìm nén, cho đi không được đáp lại, hoặc bạn đang đóng cửa trái tim. Chiếc cốc cần được rót đầy từ bên trong trước.',
    advice: 'Yêu thương bản thân trước, tình yêu bên ngoài sẽ tự tìm đến.' },
  { img: 'c2',  name: 'Two of Cups', vn: '2 Cốc', suit: 'cups',
    keywords: ['Kết nối', 'Tình yêu đôi lứa', 'Hòa hợp'],
    upright: 'Sự kết nối sâu sắc giữa hai người — tình yêu, tình bạn tri kỷ hay quan hệ đối tác ăn ý. Hai trái tim đang nhìn về một hướng.',
    reversed: 'Mất cân bằng trong quan hệ: một người cho quá nhiều, một người nhận quá nhiều. Hiểu lầm cần được nói ra.',
    advice: 'Mối quan hệ đẹp là nơi cả hai cùng rót và cùng nhận.' },
  { img: 'c3',  name: 'Three of Cups', vn: '3 Cốc', suit: 'cups',
    keywords: ['Tình bạn', 'Ăn mừng', 'Cộng đồng'],
    upright: 'Niềm vui hội ngộ, tiệc tùng và tình chị em/anh em thân thiết. Hãy tận hưởng sự nâng đỡ từ cộng đồng của bạn.',
    reversed: 'Bị cô lập khỏi nhóm bạn, tiệc tùng quá đà, hoặc người thứ ba xen vào mối quan hệ.',
    advice: 'Tình bạn chân thành là tài sản — hãy vun đắp nó.' },
  { img: 'c4',  name: 'Four of Cups', vn: '4 Cốc', suit: 'cups',
    keywords: ['Chán nản', 'Thờ ơ', 'Nhìn lại'],
    upright: 'Bạn đang chán chường, thờ ơ với những gì mình có, đến mức không nhận ra cơ hội mới đang được trao tận tay.',
    reversed: 'Giai đoạn u uất sắp qua — bạn bắt đầu mở mắt nhìn thấy những món quà xung quanh và sẵn sàng hành động trở lại.',
    advice: 'Ngẩng đầu lên — chiếc cốc thứ tư đang được trao cho bạn.' },
  { img: 'c5',  name: 'Five of Cups', vn: '5 Cốc', suit: 'cups',
    keywords: ['Mất mát', 'Tiếc nuối', 'Buồn đau'],
    upright: 'Bạn đang đắm chìm trong tiếc nuối về những gì đã đổ vỡ mà quên rằng phía sau vẫn còn hai chiếc cốc nguyên vẹn. Nỗi buồn là thật, nhưng chưa phải mất tất cả.',
    reversed: 'Bắt đầu chấp nhận và buông bỏ quá khứ. Sự tha thứ — cho người khác và cho chính mình — mở đường cho chữa lành.',
    advice: 'Khóc cho điều đã mất, rồi quay lại nhặt những gì còn nguyên.' },
  { img: 'c6',  name: 'Six of Cups', vn: '6 Cốc', suit: 'cups',
    keywords: ['Hoài niệm', 'Ký ức', 'Ngây thơ'],
    upright: 'Ký ức tuổi thơ, người cũ hoặc cảm giác ấm áp xưa quay về. Một người từ quá khứ có thể xuất hiện mang theo niềm vui giản dị.',
    reversed: 'Mắc kẹt trong quá khứ, lý tưởng hóa ngày xưa mà quên sống hiện tại. Đã đến lúc trưởng thành và bước tiếp.',
    advice: 'Quá khứ là nơi để ghé thăm, không phải nơi để ở.' },
  { img: 'c7',  name: 'Seven of Cups', vn: '7 Cốc', suit: 'cups',
    keywords: ['Ảo tưởng', 'Nhiều lựa chọn', 'Mơ mộng'],
    upright: 'Quá nhiều lựa chọn lấp lánh khiến bạn hoa mắt — nhưng phần lớn chỉ là ảo ảnh. Mơ mộng mà không hành động thì mãi là mây khói.',
    reversed: 'Sương mù tan dần, bạn bắt đầu nhìn rõ đâu là thực đâu là ảo và đưa ra quyết định dứt khoát.',
    advice: 'Chọn một chiếc cốc và cam kết với nó — đừng ôm cả bảy.' },
  { img: 'c8',  name: 'Eight of Cups', vn: '8 Cốc', suit: 'cups',
    keywords: ['Rời bỏ', 'Tìm kiếm ý nghĩa', 'Buông bỏ'],
    upright: 'Bạn quyết định rời bỏ điều từng quan trọng — không vì nó tệ, mà vì nó không còn nuôi dưỡng tâm hồn bạn. Hành trình tìm ý nghĩa sâu hơn bắt đầu.',
    reversed: 'Lưỡng lự giữa đi và ở, hoặc sợ hãi không dám rời bỏ điều đã cạn kiệt. Cũng có thể bạn đang trốn chạy thay vì đối diện.',
    advice: 'Biết khi nào nên rời đi cũng là một dạng dũng cảm.' },
  { img: 'c9',  name: 'Nine of Cups', vn: '9 Cốc', suit: 'cups',
    keywords: ['Mãn nguyện', 'Ước nguyện thành', 'Hưởng thụ'],
    upright: 'Lá bài "điều ước thành hiện thực" — sự mãn nguyện về vật chất lẫn cảm xúc. Hãy cho phép mình tận hưởng thành quả.',
    reversed: 'Thỏa mãn bề ngoài nhưng trống rỗng bên trong, hoặc ham muốn vô độ không bao giờ thấy đủ.',
    advice: 'Hạnh phúc thật sự là biết mình đã đủ.' },
  { img: 'c10', name: 'Ten of Cups', vn: '10 Cốc', suit: 'cups',
    keywords: ['Hạnh phúc viên mãn', 'Gia đình', 'Bình yên'],
    upright: 'Hạnh phúc gia đình trọn vẹn, tình yêu bền vững và cảm giác "về nhà". Đây là một trong những lá bài đẹp nhất về tình cảm.',
    reversed: 'Hình ảnh gia đình hoàn hảo che giấu rạn nứt bên trong, hoặc kỳ vọng phi thực tế về hạnh phúc.',
    advice: 'Hạnh phúc viên mãn được xây từ những điều nhỏ mỗi ngày.' },
  { img: 'c11', name: 'Page of Cups', vn: 'Tiểu Đồng Cốc', suit: 'cups',
    keywords: ['Tin tình cảm', 'Sáng tạo', 'Trực giác non trẻ'],
    upright: 'Một thông điệp tình cảm bất ngờ, lời tỏ tình hay ý tưởng sáng tạo kỳ lạ xuất hiện. Hãy đón nhận với trái tim rộng mở và chút hài hước.',
    reversed: 'Nhạy cảm thái quá, dỗi hờn trẻ con hoặc chặn đứng dòng chảy sáng tạo của chính mình.',
    advice: 'Đừng cười nhạo con cá trong cốc — điều kỳ diệu đến từ nơi bất ngờ.' },
  { img: 'c12', name: 'Knight of Cups', vn: 'Hiệp Sĩ Cốc', suit: 'cups',
    keywords: ['Lãng mạn', 'Lời mời', 'Theo đuổi lý tưởng'],
    upright: 'Chàng hiệp sĩ lãng mạn mang đến lời mời, lời tỏ tình hay đề nghị đầy cảm xúc. Hành động theo tiếng gọi trái tim.',
    reversed: 'Hứa hẹn ngọt ngào nhưng không thực hiện, tâm trạng thất thường, hoặc lý tưởng hóa người khác quá mức.',
    advice: 'Lãng mạn đẹp nhất khi đi cùng sự chân thành.' },
  { img: 'c13', name: 'Queen of Cups', vn: 'Hoàng Hậu Cốc', suit: 'cups',
    keywords: ['Thấu cảm', 'Chăm sóc', 'Trực giác sâu'],
    upright: 'Người mẹ cảm xúc — thấu hiểu, bao dung và chữa lành cho người khác bằng sự hiện diện dịu dàng. Trực giác của bạn đang rất mạnh.',
    reversed: 'Cho đi đến cạn kiệt, bị cảm xúc nhấn chìm hoặc thao túng cảm xúc người khác.',
    advice: 'Chăm sóc người khác từ chiếc cốc đầy, không phải cốc cạn.' },
  { img: 'c14', name: 'King of Cups', vn: 'Vua Cốc', suit: 'cups',
    keywords: ['Cân bằng cảm xúc', 'Bao dung', 'Khôn ngoan'],
    upright: 'Bậc thầy làm chủ cảm xúc — bình thản giữa sóng gió, khuyên bảo bằng cả lý trí lẫn trái tim. Hãy giữ sự điềm tĩnh này khi xử lý chuyện khó.',
    reversed: 'Đè nén cảm xúc đến mức lạnh lùng, hoặc dùng sự hiểu biết cảm xúc để thao túng.',
    advice: 'Cảm nhận sâu sắc nhưng không để cảm xúc cầm lái.' },

  // ============ SWORDS / KIẾM — hành Gió ============
  { img: 's1',  name: 'Ace of Swords', vn: 'Át Kiếm', suit: 'swords',
    keywords: ['Sự thật', 'Sáng tỏ', 'Đột phá tư duy'],
    upright: 'Một khoảnh khắc sáng tỏ cắt xuyên màn sương — sự thật lộ diện, ý tưởng đột phá xuất hiện. Sức mạnh của lý trí đang trong tay bạn.',
    reversed: 'Suy nghĩ rối loạn, thông tin sai lệch hoặc dùng lời nói làm tổn thương. Lưỡi kiếm sắc cần được dùng đúng chỗ.',
    advice: 'Sự thật có thể đau nhưng luôn giải phóng.' },
  { img: 's2',  name: 'Two of Swords', vn: '2 Kiếm', suit: 'swords',
    keywords: ['Bế tắc', 'Né tránh quyết định', 'Cân bằng mong manh'],
    upright: 'Bạn đang bịt mắt trước một quyết định khó, hy vọng nó tự biến mất. Sự cân bằng này chỉ là tạm thời — trì hoãn cũng là một lựa chọn, và thường là lựa chọn tệ.',
    reversed: 'Bế tắc vỡ ra, thông tin mới xuất hiện buộc bạn phải đối diện. Tháo khăn bịt mắt và nhìn thẳng.',
    advice: 'Không quyết định cũng là quyết định — hãy chọn một cách tỉnh táo.' },
  { img: 's3',  name: 'Three of Swords', vn: '3 Kiếm', suit: 'swords',
    keywords: ['Tổn thương', 'Tan vỡ', 'Nỗi đau'],
    upright: 'Trái tim bị xuyên thấu — phản bội, chia ly hay sự thật đau lòng. Nỗi đau này thật và cần được công nhận để chữa lành.',
    reversed: 'Vết thương cũ đang lành, bạn bắt đầu tha thứ và buông bỏ. Hoặc bạn đang chối bỏ nỗi đau cần được đối diện.',
    advice: 'Đau là tất yếu, nhưng khổ mãi là lựa chọn.' },
  { img: 's4',  name: 'Four of Swords', vn: '4 Kiếm', suit: 'swords',
    keywords: ['Nghỉ ngơi', 'Hồi phục', 'Tĩnh tâm'],
    upright: 'Cơ thể và tâm trí đang đòi nghỉ ngơi sau giai đoạn căng thẳng. Rút lui tạm thời không phải bỏ cuộc — đó là chiến lược.',
    reversed: 'Kiệt sức vì từ chối nghỉ ngơi, hoặc trì trệ quá lâu cần quay lại cuộc sống.',
    advice: 'Nghỉ ngơi cũng là một phần của chiến đấu.' },
  { img: 's5',  name: 'Five of Swords', vn: '5 Kiếm', suit: 'swords',
    keywords: ['Thắng bằng mọi giá', 'Xung đột', 'Mất nhiều hơn được'],
    upright: 'Chiến thắng đạt được bằng cái giá quá đắt — mất lòng người, mất uy tín. Có những trận thắng mà thực chất là thua.',
    reversed: 'Nhận ra cái giá của hơn thua, mong muốn hòa giải và khép lại xung đột.',
    advice: 'Hỏi mình: thắng trận này, bạn mất gì?' },
  { img: 's6',  name: 'Six of Swords', vn: '6 Kiếm', suit: 'swords',
    keywords: ['Chuyển tiếp', 'Rời vùng khó', 'Hành trình chữa lành'],
    upright: 'Bạn đang chèo thuyền rời khỏi vùng nước dữ sang bờ bình yên hơn. Quá trình chuyển tiếp buồn nhưng cần thiết — phía trước nhẹ nhàng hơn.',
    reversed: 'Mắc kẹt không thể rời đi, hành lý quá khứ quá nặng, hoặc chuyến đi bị trì hoãn.',
    advice: 'Mang theo bài học, bỏ lại nỗi đau.' },
  { img: 's7',  name: 'Seven of Swords', vn: '7 Kiếm', suit: 'swords',
    keywords: ['Lén lút', 'Chiến thuật', 'Lừa dối'],
    upright: 'Có sự gian dối, trốn tránh trách nhiệm hoặc hành động sau lưng — từ bạn hoặc nhắm vào bạn. Cũng có thể là lúc cần khôn khéo thay vì đối đầu trực diện.',
    reversed: 'Bí mật bị phơi bày, lương tâm thức tỉnh, hoặc bạn quyết định thôi tự lừa dối mình.',
    advice: 'Khôn khéo khác với gian dối — đừng nhầm ranh giới.' },
  { img: 's8',  name: 'Eight of Swords', vn: '8 Kiếm', suit: 'swords',
    keywords: ['Tự giam cầm', 'Bất lực', 'Niềm tin giới hạn'],
    upright: 'Bạn cảm thấy bị trói chặt không lối thoát — nhưng nhìn kỹ: dây trói lỏng và mắt chỉ bị bịt hờ. Nhà tù này phần lớn do tâm trí dựng nên.',
    reversed: 'Bạn bắt đầu thấy lối ra, gỡ bỏ niềm tin giới hạn và lấy lại quyền kiểm soát.',
    advice: 'Bước chân đầu tiên ra khỏi nhà tù là nhận ra cửa không khóa.' },
  { img: 's9',  name: 'Nine of Swords', vn: '9 Kiếm', suit: 'swords',
    keywords: ['Lo âu', 'Mất ngủ', 'Suy nghĩ tiêu cực'],
    upright: 'Những đêm trắng vì lo lắng, tội lỗi và kịch bản xấu nhất tự vẽ trong đầu. Phần lớn nỗi sợ này lớn hơn thực tế rất nhiều.',
    reversed: 'Cơn khủng hoảng dịu xuống, bạn tìm được sự giúp đỡ hoặc nhận ra nỗi sợ không có thật.',
    advice: 'Nỗi sợ trong đêm tan khi bạn dám kể nó ra dưới ánh sáng.' },
  { img: 's10', name: 'Ten of Swords', vn: '10 Kiếm', suit: 'swords',
    keywords: ['Kết thúc đau đớn', 'Chạm đáy', 'Khởi đầu mới'],
    upright: 'Một chương khép lại theo cách đau đớn nhất — phản bội, sụp đổ, kiệt quệ. Nhưng đây là đáy: từ đây chỉ còn đường đi lên, và bình minh đã hiện ở chân trời.',
    reversed: 'Hồi phục sau biến cố, vết thương liền da. Điều tồi tệ nhất đã qua.',
    advice: 'Khi không thể tệ hơn, mọi thay đổi đều là đi lên.' },
  { img: 's11', name: 'Page of Swords', vn: 'Tiểu Đồng Kiếm', suit: 'swords',
    keywords: ['Tò mò', 'Cảnh giác', 'Tin tức'],
    upright: 'Tâm trí nhanh nhạy, ham học hỏi và đầy câu hỏi. Tin tức hoặc ý tưởng mới đến — hãy kiểm chứng kỹ trước khi tin.',
    reversed: 'Nói nhiều hơn làm, tò mò thành soi mói, hoặc lời nói thiếu suy nghĩ gây rắc rối.',
    advice: 'Hỏi để hiểu, không phải để bắt bẻ.' },
  { img: 's12', name: 'Knight of Swords', vn: 'Hiệp Sĩ Kiếm', suit: 'swords',
    keywords: ['Quyết liệt', 'Tham vọng', 'Hấp tấp'],
    upright: 'Lao thẳng vào mục tiêu với tốc độ và sự quyết liệt tối đa. Hiệu quả khi cần hành động nhanh, nhưng dễ giẫm đạp cảm xúc người khác.',
    reversed: 'Hung hăng thiếu kiểm soát, tranh cãi vô nghĩa, hoặc năng lượng bị phân tán.',
    advice: 'Tốc độ không thay được phương hướng.' },
  { img: 's13', name: 'Queen of Swords', vn: 'Hoàng Hậu Kiếm', suit: 'swords',
    keywords: ['Sắc sảo', 'Độc lập', 'Thẳng thắn'],
    upright: 'Người phụ nữ sắc sảo nhìn thấu mọi giả dối, nói thẳng và quyết định bằng lý trí. Kinh nghiệm đau thương đã tôi luyện thành trí tuệ.',
    reversed: 'Lạnh lùng cay nghiệt, dùng lời nói làm vũ khí, hoặc để cay đắng quá khứ chi phối.',
    advice: 'Thẳng thắn với lòng trắc ẩn — đó là đỉnh cao của giao tiếp.' },
  { img: 's14', name: 'King of Swords', vn: 'Vua Kiếm', suit: 'swords',
    keywords: ['Lý trí', 'Công bằng', 'Uy quyền trí tuệ'],
    upright: 'Bậc thầy của tư duy logic và sự công minh — phán đoán dựa trên sự thật, không thiên vị. Thời điểm cần cái đầu lạnh và nguyên tắc rõ ràng.',
    reversed: 'Lạm dụng quyền lực trí tuệ, phán xét khắc nghiệt, hoặc thông minh mà thiếu đạo đức.',
    advice: 'Quyền lực lớn nhất của lý trí là phục vụ công lý.' },

  // ============ PENTACLES / XU — hành Đất ============
  { img: 'p1',  name: 'Ace of Pentacles', vn: 'Át Xu', suit: 'pentacles',
    keywords: ['Cơ hội tài chính', 'Khởi đầu vững chắc', 'Thịnh vượng'],
    upright: 'Một cơ hội vật chất cụ thể được trao tận tay: việc làm mới, khoản đầu tư, nguồn thu nhập. Hạt giống thịnh vượng đang chờ được gieo.',
    reversed: 'Cơ hội vụt mất, kế hoạch tài chính thiếu nền tảng, hoặc quá tập trung vào tiền mà quên giá trị khác.',
    advice: 'Cơ hội tốt cần đôi tay thực tế để thành hình.' },
  { img: 'p2',  name: 'Two of Pentacles', vn: '2 Xu', suit: 'pentacles',
    keywords: ['Cân bằng', 'Đa nhiệm', 'Linh hoạt'],
    upright: 'Bạn đang tung hứng nhiều trách nhiệm — công việc, tiền bạc, gia đình — và vẫn giữ được nhịp. Sự linh hoạt là chìa khóa, nhưng đừng nhận thêm.',
    reversed: 'Quả bóng bắt đầu rơi: quá tải, lỡ hạn, tài chính mất cân đối. Cần sắp xếp lại ưu tiên ngay.',
    advice: 'Cân bằng không phải giữ mọi thứ — mà là biết thứ gì đáng giữ.' },
  { img: 'p3',  name: 'Three of Pentacles', vn: '3 Xu', suit: 'pentacles',
    keywords: ['Teamwork', 'Tay nghề', 'Được công nhận'],
    upright: 'Tay nghề của bạn được công nhận và sự hợp tác đang sinh quả ngọt. Mỗi người một thế mạnh — công trình lớn cần nhiều bàn tay.',
    reversed: 'Làm việc nhóm trục trặc, thiếu tôn trọng chuyên môn của nhau, hoặc chất lượng bị xem nhẹ.',
    advice: 'Giỏi một mình là tốt, hợp tác giỏi là xuất sắc.' },
  { img: 'p4',  name: 'Four of Pentacles', vn: '4 Xu', suit: 'pentacles',
    keywords: ['Giữ chặt', 'An toàn', 'Kiểm soát'],
    upright: 'Bạn đang ôm chặt tiền bạc, quyền kiểm soát hay con người vì sợ mất. An toàn đấy, nhưng tay ôm xu thì không thể nhận thêm gì mới.',
    reversed: 'Bắt đầu nới lỏng — chi tiêu thoáng hơn, chia sẻ nhiều hơn. Hoặc ngược lại: mất kiểm soát tài chính.',
    advice: 'Tiền là dòng chảy — giữ chặt quá thì nó tù đọng.' },
  { img: 'p5',  name: 'Five of Pentacles', vn: '5 Xu', suit: 'pentacles',
    keywords: ['Khó khăn tài chính', 'Bị bỏ rơi', 'Khủng hoảng'],
    upright: 'Giai đoạn thiếu thốn về tiền bạc, sức khỏe hoặc cảm giác bị bỏ rơi ngoài lề. Nhưng ánh sáng cứu giúp ở rất gần — đừng vì kiêu hãnh mà không gõ cửa.',
    reversed: 'Khó khăn dần qua, tìm được sự giúp đỡ, sức khỏe và tài chính hồi phục.',
    advice: 'Xin giúp đỡ không phải yếu đuối — đó là khôn ngoan.' },
  { img: 'p6',  name: 'Six of Pentacles', vn: '6 Xu', suit: 'pentacles',
    keywords: ['Cho và nhận', 'Hào phóng', 'Công bằng'],
    upright: 'Dòng chảy cho-nhận đang cân bằng: bạn được giúp đỡ đúng lúc, hoặc đủ đầy để giúp người khác. Sự hào phóng gieo hôm nay là phúc của ngày mai.',
    reversed: 'Cho đi kèm điều kiện, nợ nần ràng buộc, hoặc bố thí để củng cố quyền lực.',
    advice: 'Cho đi không toan tính là khoản đầu tư lãi nhất.' },
  { img: 'p7',  name: 'Seven of Pentacles', vn: '7 Xu', suit: 'pentacles',
    keywords: ['Kiên nhẫn', 'Đánh giá lại', 'Đầu tư dài hạn'],
    upright: 'Cây bạn trồng đang lớn nhưng chưa đến mùa hái. Dừng lại đánh giá: nỗ lực này có đáng tiếp tục không? Kiên nhẫn là khoản đầu tư khó nhất.',
    reversed: 'Sốt ruột vì kết quả chậm, đầu tư sai chỗ, hoặc bỏ cuộc ngay trước mùa thu hoạch.',
    advice: 'Đừng nhổ cây lên xem rễ đã mọc chưa.' },
  { img: 'p8',  name: 'Eight of Pentacles', vn: '8 Xu', suit: 'pentacles',
    keywords: ['Rèn luyện', 'Tinh thông', 'Chuyên tâm'],
    upright: 'Giai đoạn mài giũa tay nghề bằng sự chuyên tâm tuyệt đối — từng đồng xu một, từng chi tiết một. Con đường đến tinh thông không có lối tắt.',
    reversed: 'Làm việc qua loa, lặp lại máy móc không tiến bộ, hoặc cầu toàn đến mức tê liệt.',
    advice: 'Nghề tinh thì thân vinh — đầu tư vào kỹ năng không bao giờ lỗ.' },
  { img: 'p9',  name: 'Nine of Pentacles', vn: '9 Xu', suit: 'pentacles',
    keywords: ['Độc lập tài chính', 'Tự thưởng', 'Thành quả'],
    upright: 'Bạn đã tự tay xây nên khu vườn sung túc của riêng mình — độc lập, sang trọng và tự do. Hãy tận hưởng thành quả mà không cần ai cho phép.',
    reversed: 'Phụ thuộc tài chính, tiêu xài vượt khả năng, hoặc giàu có mà cô đơn.',
    advice: 'Sự xa xỉ lớn nhất là tự do do chính mình tạo ra.' },
  { img: 'p10', name: 'Ten of Pentacles', vn: '10 Xu', suit: 'pentacles',
    keywords: ['Di sản', 'Giàu có bền vững', 'Gia tộc'],
    upright: 'Sự thịnh vượng đa thế hệ — tài sản, truyền thống và nền tảng gia đình vững chắc. Những gì bạn xây hôm nay sẽ còn lại cho đời sau.',
    reversed: 'Tranh chấp tài sản gia đình, nền tảng tài chính lung lay, hoặc giàu có đánh đổi bằng hạnh phúc.',
    advice: 'Giàu nhất là người để lại được giá trị cho thế hệ sau.' },
  { img: 'p11', name: 'Page of Pentacles', vn: 'Tiểu Đồng Xu', suit: 'pentacles',
    keywords: ['Học hỏi', 'Cơ hội mới', 'Thực tế'],
    upright: 'Tinh thần ham học và khát khao xây dựng điều cụ thể: khóa học mới, công việc đầu tiên, dự án khởi nghiệp nhỏ. Hạt mầm tham vọng đang nảy.',
    reversed: 'Trì hoãn, học không hành, hoặc mơ về kết quả mà ngại bắt tay vào việc.',
    advice: 'Học bằng cách làm — đồng xu đầu tiên quý nhất.' },
  { img: 'p12', name: 'Knight of Pentacles', vn: 'Hiệp Sĩ Xu', suit: 'pentacles',
    keywords: ['Chăm chỉ', 'Đáng tin', 'Bền bỉ'],
    upright: 'Người làm việc bền bỉ nhất bộ bài — chậm mà chắc, nói ít làm nhiều, không bao giờ bỏ dở. Thành công đến từ kỷ luật lặp lại mỗi ngày.',
    reversed: 'Trì trệ, bảo thủ ngại thay đổi, hoặc làm việc như máy mà quên mất mục đích.',
    advice: 'Chậm mà đều thắng nhanh mà đứt quãng.' },
  { img: 'p13', name: 'Queen of Pentacles', vn: 'Hoàng Hậu Xu', suit: 'pentacles',
    keywords: ['Đảm đang', 'Nuôi dưỡng', 'Thực tế ấm áp'],
    upright: 'Người phụ nữ vừa giỏi việc nước vừa đảm việc nhà — chăm lo cho mọi người bằng sự thực tế ấm áp. Tài chính và tổ ấm đều trong tay bạn.',
    reversed: 'Ôm đồm đến kiệt sức, bỏ bê bản thân, hoặc quá đặt nặng vật chất trong quan hệ.',
    advice: 'Chăm sóc tổ ấm bắt đầu từ chăm sóc chính mình.' },
  { img: 'p14', name: 'King of Pentacles', vn: 'Vua Xu', suit: 'pentacles',
    keywords: ['Thành đạt', 'Vững vàng', 'Trụ cột'],
    upright: 'Đỉnh cao của thành công vật chất — doanh nhân vững vàng, trụ cột đáng tin, chạm đâu thắng đó. Sự giàu có này xây bằng năng lực và kỷ luật thật.',
    reversed: 'Tham lam, cứng nhắc, dùng tiền đo mọi giá trị hoặc kiểm soát người khác bằng vật chất.',
    advice: 'Người giàu thật sự khiến người quanh mình cùng thịnh vượng.' },
];

const SUITS = {
  wands:     { vn: 'Gậy',  en: 'Wands',     element: '🔥 Lửa',  domain: 'đam mê, sự nghiệp và hành động' },
  cups:      { vn: 'Cốc',  en: 'Cups',      element: '💧 Nước', domain: 'tình cảm, trực giác và các mối quan hệ' },
  swords:    { vn: 'Kiếm', en: 'Swords',    element: '🌬️ Gió',  domain: 'tư duy, giao tiếp và thử thách' },
  pentacles: { vn: 'Xu',   en: 'Pentacles', element: '🌍 Đất',  domain: 'tiền bạc, công việc và vật chất' },
};
